In [53]:
import numpy as np

# Listy w Pythonie

In [17]:
l1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
type(l1)

list

In [20]:
l1[3] = 5
l1

[0, 1, 2, 5, 4, 5, 6, 7, 8, 9]

In [21]:
l1[3] = 'xD'
l1

[0, 1, 2, 'xD', 4, 5, 6, 7, 8, 9]

In [22]:
l1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
l1[2:7]

[2, 3, 4, 5, 6]

In [24]:
l1[:5]

[0, 1, 2, 3, 4]

In [25]:
l1[5:]

[5, 6, 7, 8, 9]

In [28]:
l1[2:8:3]

[2, 5]

In [30]:
l1[-2]

8

In [31]:
l1[1:-3]

[1, 2, 3, 4, 5, 6]

In [33]:
l1[::2]

[0, 2, 4, 6, 8]

In [34]:
l1[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [35]:
l2 = l1[:5]
l2

[0, 1, 2, 3, 4]

In [37]:
l2[2] = 10
l2, l1

([0, 1, 10, 3, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
l1[:2] = [99, 98]
l1

[99, 98, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
# l1[:2] = 5

In [42]:
l1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l2 = l1[::-1]
l1, l2

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
l1 * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [48]:
# l1 * 3.5

In [50]:
# l1 + 1

In [51]:
l1 + l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# NumPy

In [56]:
a1 = np.array(l1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
type(a1)

numpy.ndarray

In [58]:
a1.dtype

dtype('int32')

In [59]:
a1[4]

4

In [61]:
# a1[4] = 'xD'

In [62]:
a1 = np.array(l1, dtype=np.float64)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
a1 = np.array(l1, dtype=np.int64)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [64]:
a1 = np.array(l1, dtype=np.complex128)
a1

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [66]:
np.zeros(10), np.zeros(10, dtype=np.int64)  

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [67]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
np.ones_like(a1)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [72]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [74]:
np.linspace(0, 2 * np.pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [75]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [77]:
a1 = np.array(l1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[3:6] = 7
a1

array([0, 1, 2, 7, 7, 7, 6, 7, 8, 9])

In [79]:
a1 = np.array(l1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a2 = a1[3:6]
a2

array([3, 4, 5])

In [82]:
a2[0] = 1000
a2, a1

(array([1000,    4,    5]),
 array([   0,    1,    2, 1000,    4,    5,    6,    7,    8,    9]))

In [83]:
a1.copy()

array([   0,    1,    2, 1000,    4,    5,    6,    7,    8,    9])

In [85]:
a1 * 2

array([   0,    2,    4, 2000,    8,   10,   12,   14,   16,   18])

In [87]:
a1 + 2

array([   2,    3,    4, 1002,    6,    7,    8,    9,   10,   11])

In [88]:
a1 = np.array(l1)
a2 = np.array(l2)
a1, a2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [89]:
a1 + a2

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [90]:
a1 / a2

C:\Users\macie\AppData\Local\Temp\ipykernel_35848\108435935.py:1: RuntimeWarning: divide by zero encountered in divide
  a1 / a2


array([0.        , 0.125     , 0.28571429, 0.5       , 0.8       ,
       1.25      , 2.        , 3.5       , 8.        ,        inf])

In [91]:
np.concatenate((a1, a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [92]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
m1.shape

(3, 3)

In [96]:
a1.shape, len(a1)

((10,), 10)

In [99]:
m2 = np.ones((3, 3))
m2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
m1[:, 1]

array([2, 5, 8])

In [102]:
m1 * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [103]:
m1 * m2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [108]:
m1 @ m2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [109]:
np.dot(m1, m2)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])